application: mfrsc
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /public/
  static_dir: public
  
- url: /.*
  script: main.app
  
libraries:
- name: jinja2
  version: "2.6"
  
- name: webapp2
  version: "2.3"
  
- name: lxml
  version: "2.3"
  
